# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('request1', models.CharField(max_length=100)),
                ('request2', models.CharField(max_length=100)),
                ('request3', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=200)),
            ],
        ),
    ]
