# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=100)),
                ('prodImg', models.CharField(max_length=400)),
                ('isAdded', models.BooleanField(default=False)),
            ],
        ),
    ]
