# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='birthday',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='ethnicity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='satisfaction',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
