# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0004_auto_20160720_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='satisfaction',
        ),
        migrations.AddField(
            model_name='request',
            name='additionalItems',
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
