# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0005_auto_20160720_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='additionalItems',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='request',
            name='birthday',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='ethnicity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='request2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='request3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='why',
            field=models.CharField(default='', max_length=200),
        ),
    ]
