# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0006_auto_20160720_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='name',
        ),
        migrations.AddField(
            model_name='request',
            name='diet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='religiousDiet',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='zipcode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
