# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0008_auto_20160721_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='satisfaction',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
