# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationDate', models.DateTimeField(auto_now_add=True)),
                ('donationName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orderNum', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('quantity', models.IntegerField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations1', to='dashboard.UserProfile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='dashboard.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('FP', 'Fresh Produce'), ('CS', 'Canned Goods & Soup'), ('BM', 'Boxed Meals'), ('GR', 'Grains, Rice, Beans'), ('HE', 'Household Essentials'), ('CL', 'Clothing'), ('O', 'Others')], max_length=2)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos/product')),
                ('quantity', models.IntegerField(default=0)),
                ('numDonated', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dashboard.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('request1', models.CharField(max_length=100)),
                ('request2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('request3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('why1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('why2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('why3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('satisfaction', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('additionalItems', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('ethnicity', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('birthday', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('diet', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('religiousDiet', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.Organization')),
            ],
        ),
    ]
