# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('prodImg', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('prodType', models.CharField(blank=True, default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('request1', models.CharField(max_length=100)),
                ('request2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('request3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('why1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('why2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('why3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('satisfaction', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('additionalItems', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('ethnicity', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('birthday', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('diet', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('religiousDiet', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
