# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationDate', models.DateTimeField(auto_now_add=True)),
                ('orderNum', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('quantity', models.IntegerField()),
                ('donorID', models.IntegerField()),
            ],
        ),
    ]
