# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('site_url', models.URLField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos/org')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos/profile')),
                ('user_type', models.CharField(choices=[('O', 'Org User'), ('D', 'Donor')], default='D', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='dashboard.UserProfile'),
        ),
    ]
