# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='userProfile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='dashboard.UserProfile'),
        ),
    ]
